### ISSUE TITLE
Plugin works for too long

### ISSUE THREAD

**Issue by snowindy** [tolyo/html-pages-brunch#1]
Hey,
I tried to place all files (~1000 html files) that previously were in assets folder to app folder.
This was done to make html and corresponding js files close to each other - so I don't have dig into assets folder every time I work on js file.

I tried to switch off the minifier with config, it did not help.

brunch watch: before this change it took ~ 4s to complete initial watch iteration
brunch watch: after this change it took more than 5 minutes, I stopped waiting and cancelled

I used this config:

```
plugins:
    htmlPages:
      removeComments: false
      removeCommentsFromCDATA: false
      removeCDATASectionsFromCDATA: false
      collapseBooleanAttributes: false
      useShortDoctype: false
      removeEmptyAttributes: false
      removeScriptTypeAttributes: false
      removeStyleLinkTypeAttributes: false
      collapseWhitespace: false
      minifyJS: false
      minifyCSS: false
      destination : (path) -> path.replace /^app[\/\\](.*)\.html$/, "$1.html"

```
